[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.31"

[features]
seeds = false
skip-lint = false

[programs.localnet]
tristero = "BeGgJzgrshaSYVzS4Ut9CPWMHFPWfnJgfGUqiFDztGYe"
endpoint = "2PKFUuGQdpsVt8U4RpuFY373gXiubsen8VSzP7NWyexe"

[programs.testnet]
tristero = "BeGgJzgrshaSYVzS4Ut9CPWMHFPWfnJgfGUqiFDztGYe"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 10000000 tests/**/*.ts"
